version: '3.8'
services:
  app:
    build: .
    environment:
      - DISABLE_ESLINT_PLUGIN=true
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5193:5173
    command: npm run dev